Organizations:
  - &MedTechChainOrderer
    Name: MedTechChainOrderer
    SkipAsForeign: false
    ID: MedTechChainOrdererMSP
    MSPDir: ../../../.generated/crypto/ordererOrganizations/medtechchain.nl/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MedTechChainOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('MedTechChainOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('MedTechChainOrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MedTechChainOrdererMSP.member')"
    OrdererEndpoints:
      - "orderer0.medtechchain.nl:7050"

  - &MedTechChainPeer
    Name: MedTechChainPeer
    SkipAsForeign: false
    ID: MedTechChainPeerMSP
    MSPDir: ../../../.generated/crypto/peerOrganizations/medtechchain.nl/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MedTechChainPeerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('MedTechChainPeerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('MedTechChainPeerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MedTechChainPeerMSP.member')"

  - &MediValeOrderer
    Name: MediValeOrderer
    SkipAsForeign: false
    ID: MediValeOrdererMSP
    MSPDir: ../../../.generated/crypto/ordererOrganizations/medivale.nl/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.member')"
    OrdererEndpoints:
      - "orderer0.medivale.nl:7050"

  - &MediValePeer
    Name: MediValePeer
    SkipAsForeign: false
    ID: MediValePeerMSP
    MSPDir: ../../../.generated/crypto/peerOrganizations/medivale.nl/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MediValePeerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('MediValePeerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('MediValePeerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MediValePeerMSP.member')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  ACLs: &ACLsDefault
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Writers

    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers

    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers

    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetChannelConfig: /Channel/Application/Readers

    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Writers

    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers

  Organizations:

  Policies: &ApplicationDefaultPolicies
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"  # Simplified; should use MAJORITY
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"  # Simplified; should use MAJORITY
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins" # Simplified; should use MAJORITY

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  Addresses:

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 500
    AbsoluteMaxBytes: 10 MB
    PreferredMaxBytes: 2 MB

  MaxChannels: 0

  EtcdRaft:
    Consenters:
      - Host: orderer0.medtechchain.nl
        Port: 7050
        ClientTLSCert: ../../../.generated/crypto/ordererOrganizations/medtechchain.nl/orderers/orderer0.medtechchain.nl/tls/server.crt
        ServerTLSCert: ../../../.generated/crypto/ordererOrganizations/medtechchain.nl/orderers/orderer0.medtechchain.nl/tls/server.crt
      - Host: orderer0.medivale.nl
        Port: 7050
        ClientTLSCert: ../../../.generated/crypto/ordererOrganizations/medivale.nl/orderers/orderer0.medivale.nl/tls/server.crt
        ServerTLSCert: ../../../.generated/crypto/ordererOrganizations/medivale.nl/orderers/orderer0.medivale.nl/tls/server.crt

    Options:
      TickInterval: 500ms
      ElectionTick: 10
      HeartbeatTick: 1
      MaxInflightBlocks: 5
      SnapshotIntervalSize: 16 MB

  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"  # Simplified; should use MAJORITY
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"  # Simplified; should use MAJORITY

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  MedTechChainGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *MedTechChainOrderer
        - *MediValeOrderer
    Consortiums:
      MedTechChainConsortium:
        Organizations:
          - *MedTechChainPeer
          - *MediValePeer

  MedTechChainChannel:
    <<: *ChannelDefaults
    Consortium: MedTechChainConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *MedTechChainPeer
        - *MediValePeer
