OrdererOrgs:
  - Name: MedTechChain
    Domain: medtechchain.nl
    Specs:
      - Hostname: orderer
  - Name: MediVale
    Domain: medivale.nl
    Specs:
      - Hostname: orderer
  - Name: HealPoint
    Domain: healpoint.nl
    Specs:
      - Hostname: orderer
  - Name: LifeCare
    Domain: lifecare.nl
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: MedTechChain
    Domain: medtechchain.nl
    EnableNodeOUs: false
    Specs:
      - Hostname: peer
    Users:
      Count: 1

  - Name: MediVale
    Domain: medivale.nl
    EnableNodeOUs: false
    Specs:
      - Hostname: peer
    Users:
      Count: 1

  - Name: HealPoint
    Domain: healpoint.nl
    EnableNodeOUs: false
    Specs:
      - Hostname: peer
    Users:
      Count: 1

  - Name: LifeCare
    Domain: lifecare.nl
    EnableNodeOUs: false
    Specs:
      - Hostname: peer
    Users:
      Count: 1


