version: '3.8'

services:
  explorerdb.medtechchain.nl:
    image: ghcr.io/hyperledger-labs/explorer-db:${EXPLORER_IMAGE_VERSION}
    container_name: explorerdb.medtechchain.nl
    hostname: explorerdb.medtechchain.nl
    environment:
      - DATABASE_DATABASE=medtechchain
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blockchain-explorer

  explorer.medtechchain.nl:
    image: ghcr.io/hyperledger-labs/explorer:${EXPLORER_IMAGE_VERSION}
    container_name: explorer.medtechchain.nl
    hostname: explorer.medtechchain.nl
    environment:
      - DATABASE_HOST=explorerdb.medtechchain.nl
      - DATABASE_DATABASE=medtechchain
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWD=admin
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=${PORT:-8080}
    volumes:
      - ${EXPLORER_CONFIG_FILE_PATH}:/opt/explorer/app/platform/fabric/config.json
      - ${EXPLORER_PROFILE_DIR_PATH}:/opt/explorer/app/platform/fabric/connection-profile
      - ${FABRIC_CRYPTO_PATH}:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    depends_on:
      explorerdb.medtechchain.nl:
        condition: service_healthy
    networks:
      - internet
      - blockchain-explorer

volumes:
  pgdata:
  walletstore:

networks:
  blockchain-explorer:
    name: "blockchain-explorer"  
  internet:
    external: true
    name: "global"