################################################################################
#
#   Capabilities
#
################################################################################
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

################################################################################
#
#   Organizations
#
################################################################################
Organizations:
  - &HealthBlocks
    Name: HealthBlocks
    ID: HealthBlocksMSP
    MSPDir: ../../.generated/cryptogen/ordererOrganizations/healthblocks.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HealthBlocksMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('HealthBlocksMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('HealthBlocksMSP.admin')"
    OrdererEndpoints:
      - healthblocks.com:7050

  - &MediVale
    Name: Medivale
    ID: MedivaleMSP
    MSPDir: ../../.generated/cryptogen/ordererOrganizations/medivale.com/msp
    Policies: 
      Readers:
        Type: Signature
        Rule: "OR('MedivaleMSP.admin', 'MedivaleMSP.peer', 'MedivaleMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MedivaleMSP.admin', 'MedivaleMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MedivaleMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MedivaleMSP.peer')"
    OrdererEndpoints:
      - medivale.com:7050

  - &HealPoint
    Name: HealPoint
    ID: HealPointMSP
    MSPDir: ../../.generated/cryptogen/ordererOrganizations/healpoint.com/msp
    Policies: 
      Readers:
        Type: Signature
        Rule: "OR('HealPointMSP.admin', 'HealPointMSP.peer', 'HealPointMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('HealPointMSP.admin', 'HealPointMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('HealPointMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('HealPointMSP.peer')"
    OrdererEndpoints:
      - healpoint.com:7050

  - &LifeCare
    Name: LifeCare
    ID: LifeCareMSP
    MSPDir: ../../.generated/cryptogen/ordererOrganizations/lifecare.com/msp
    Policies: 
      Readers:
        Type: Signature
        Rule: "OR('LifeCareMSP.admin', 'LifeCareMSP.peer', 'LifeCareMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('LifeCareMSP.admin', 'LifeCareMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('LifeCareMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('LifeCareMSP.peer')"
    OrdererEndpoints:
      - lifecare.com:7050

################################################################################
#
#   Defaults - Application
#
################################################################################
Application: &ApplicationDefaults
  Capabilities:
    <<: *ApplicationCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Organizations:

################################################################################
#
#   Defaults - Orderer
#
################################################################################
Orderer: &OrdererDefaults
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

################################################################################
#
#   Defaults - Channel
#
################################################################################
Channel: &ChannelDefaults
  Capabilities:
    <<: *ChannelCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

################################################################################
#
#   Profiles
#
################################################################################
Profiles:
  HealthBlocks:
    <<: *ChannelDefaults
    Consortiums:
      MedicalMetadata:
        Organizations:
          - *HealthBlocks
          - *MediVale
          - *HealPoint
          - *LifeCare
    Consortium: MedicalMetadata
    Orderer:
      <<: *OrdererDefaults
      Capabilities: *OrdererCapabilities
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: healthblocks.com
            Port: 7050
            ClientTLSCert: ../../.generated/cryptogen/ordererOrganizations/healthblocks.com/orderers/orderer.healthblocks.com/tls/server.crt
            ServerTLSCert: ../../.generated/cryptogen/ordererOrganizations/healthblocks.com/orderers/orderer.healthblocks.com/tls/server.crt
          - Host: medivale.com
            Port: 7050
            ClientTLSCert: ../../.generated/cryptogen/ordererOrganizations/medivale.com/orderers/orderer.medivale.com/tls/server.crt
            ServerTLSCert: ../../.generated/cryptogen/ordererOrganizations/medivale.com/orderers/orderer.medivale.com/tls/server.crt
          - Host: healpoint.com
            Port: 7050
            ClientTLSCert: ../../.generated/cryptogen/ordererOrganizations/healpoint.com/orderers/orderer.healpoint.com/tls/server.crt
            ServerTLSCert: ../../.generated/cryptogen/ordererOrganizations/healpoint.com/orderers/orderer.healpoint.com/tls/server.crt
          - Host: lifecare.com
            Port: 7050
            ClientTLSCert: ../../.generated/cryptogen/ordererOrganizations/lifecare.com/orderers/orderer.lifecare.com/tls/server.crt
            ServerTLSCert: ../../.generated/cryptogen/ordererOrganizations/lifecare.com/orderers/orderer.lifecare.com/tls/server.crt
      Organizations:
        - *HealthBlocks
        - *MediVale
        - *HealPoint
        - *LifeCare
    Application:
      <<: *ApplicationDefaults
      Capabilities: *ApplicationCapabilities
      Organizations:
        - *HealthBlocks
        - *MediVale
        - *HealPoint
        - *LifeCare


