version: '3.8'

x-orderer-config-override: &orderer_config_override
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0

  ORDERER_GENERAL_BOOTSTRAPMETHOD: file
  ORDERER_GENERAL_BOOTSTRAPFILE: /var/hyperledger/genesis/medtechchain-genesis.block  

  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/msp
  ORDERER_GENERAL_LOCALMSPID: MediValeOrdererMSP

  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/tls/server.key
  ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/tls/server.crt
  ORDERER_GENERAL_TLS_ROOTCAS: "[/var/hyperledger/tls/ca.crt]"  

x-core-config-override: &core_config_override
  CORE_PEER_NETWORKID: medivale

  CORE_PEER_MSPCONFIGPATH: /var/hyperledger/msp
  CORE_PEER_LOCALMSPID: MediValePeerMSP

  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_PEER_GOSSIP_ORGLEADER: "false"

  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /var/hyperledger/tls/server.crt
  CORE_PEER_TLS_KEY_FILE: /var/hyperledger/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /var/hyperledger/tls/ca.crt

  CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: medivale

x-peer-defaults: &peer_defaults
    image: hyperledger/fabric-peer:$FABRIC_IMAGE_TAG
    working_dir: /home/peer/scripts
    environment: &peer_env_vars
      FABRIC_CFG_PATH: /var/hyperledger/config
      FABRIC_LOGGING_SPEC: INFO
      <<: *core_config_override
    command: peer node start
    depends_on: 
      - orderer.medivale.nl
    networks:
      - medivale
      - tools

services:
  orderer.medivale.nl:
    container_name: orderer.medivale.nl
    image: hyperledger/fabric-orderer:$FABRIC_IMAGE_TAG
    environment:
      FABRIC_CFG_PATH: /var/hyperledger/config
      FABRIC_LOGGING_SPEC: INFO
      <<: *orderer_config_override
    command: orderer
    volumes:
    - ./configs/nodes/orderer:/var/hyperledger/config
    - ./.generated/configtx/genesis:/var/hyperledger/genesis
    - ./.generated/crypto/ordererOrganizations/medivale.nl/orderers/orderer.medivale.nl/msp:/var/hyperledger/msp
    - ./.generated/crypto/ordererOrganizations/medivale.nl/orderers/orderer.medivale.nl/tls:/var/hyperledger/tls
    - orderer.medivale.nl:/var/ledger
    ports:
      - 8050:7050
    networks:
      - medivale
      - internet
      - tools

  peer0.medivale.nl:
    <<: *peer_defaults
    container_name: peer0.medivale.nl
    environment:
      <<: *peer_env_vars
      CORE_PEER_ID: peer0.medivale.nl
      CORE_PEER_GOSSIP_BOOTSTRAP: "peer1.medivale.nl:7051 peer2.medivale.nl:7051"
    volumes:
      # chaincode docker mount
      - /var/run/:/var/run/

      # peer config
      - ./configs/nodes/peer:/var/hyperledger/config

      # node msp & tls
      - ./.generated/crypto/peerOrganizations/medivale.nl/peers/peer0.medivale.nl/msp:/var/hyperledger/msp
      - ./.generated/crypto/peerOrganizations/medivale.nl/peers/peer0.medivale.nl/tls:/var/hyperledger/tls

      # orderer tlscacert to create / join the channel
      - ./.generated/crypto/ordererOrganizations/medivale.nl/orderers/orderer.medivale.nl/msp/tlscacerts:/var/hyperledger/orderer-tlscacert

      # admin msp to create / join the channel
      - ./.generated/crypto/peerOrganizations/medivale.nl/users/Admin@medivale.nl/msp:/var/hyperledger/admin/msp
      
      # scripts
      - ./scripts/peer:/home/peer/scripts

      # blocks persistance
      - peer0.medivale.nl:/var/hyperledger

  peer1.medivale.nl:
    <<: *peer_defaults
    container_name: peer1.medivale.nl
    environment:
      <<: *peer_env_vars
      CORE_PEER_ID: peer1.medivale.nl
      CORE_PEER_GOSSIP_BOOTSTRAP: "peer0.medivale.nl:7051 peer2.medivale.nl:7051"
    volumes:
      # chaincode docker mount
      - /var/run/:/var/run/

      # peer config
      - ./configs/nodes/peer:/var/hyperledger/config

      # node msp & tls
      - ./.generated/crypto/peerOrganizations/medivale.nl/peers/peer1.medivale.nl/msp:/var/hyperledger/msp
      - ./.generated/crypto/peerOrganizations/medivale.nl/peers/peer1.medivale.nl/tls:/var/hyperledger/tls

      # orderer tlscacert to create / join the channel
      - ./.generated/crypto/ordererOrganizations/medivale.nl/orderers/orderer.medivale.nl/msp/tlscacerts:/var/hyperledger/orderer-tlscacert

      # admin msp to create / join the channel
      - ./.generated/crypto/peerOrganizations/medivale.nl/users/Admin@medivale.nl/msp:/var/hyperledger/admin/msp
      
      # scripts
      - ./scripts/peer:/home/peer/scripts

      # blocks persistance
      - peer1.medivale.nl:/var/hyperledger

  peer2.medivale.nl:
    <<: *peer_defaults
    container_name: peer2.medivale.nl
    environment:
      <<: *peer_env_vars
      CORE_PEER_ID: peer2.medivale.nl
      CORE_PEER_GOSSIP_BOOTSTRAP: "peer0.medivale.nl:7051 peer1.medivale.nl:7051"
    volumes:
      # chaincode docker mount
      - /var/run/:/var/run/

      # peer config
      - ./configs/nodes/peer:/var/hyperledger/config

      # node msp & tls
      - ./.generated/crypto/peerOrganizations/medivale.nl/peers/peer2.medivale.nl/msp:/var/hyperledger/msp
      - ./.generated/crypto/peerOrganizations/medivale.nl/peers/peer2.medivale.nl/tls:/var/hyperledger/tls

      # orderer tlscacert to create / join the channel
      - ./.generated/crypto/ordererOrganizations/medivale.nl/orderers/orderer.medivale.nl/msp/tlscacerts:/var/hyperledger/orderer-tlscacert

      # admin msp to create / join the channel
      - ./.generated/crypto/peerOrganizations/medivale.nl/users/Admin@medivale.nl/msp:/var/hyperledger/admin/msp

      # scripts
      - ./scripts/peer:/home/peer/scripts

      # blocks persistance
      - peer2.medivale.nl:/var/hyperledger

volumes:
  orderer.medivale.nl:
  peer0.medivale.nl:
  peer1.medivale.nl:
  peer2.medivale.nl:

networks:
  medivale:
    external: true
    name: "medivale"
  tools:
    external: true
    name: "fabric-tools"
  internet:
    external: true
    name: "internet"