Organizations:
  - &HealthBlocksOrderer
    Name: HealthBlocksOrderer
    SkipAsForeign: false
    ID: HealthBlocksOrdererMSP
    MSPDir: ../../.generated/crypto/ordererOrganizations/healthblocks.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HealthBlocksOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('HealthBlocksOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('HealthBlocksOrdererMSP.admin')"
    OrdererEndpoints:
      - "orderer.healthblocks.com:7050"

  - &HealthBlocksPeer
    Name: HealthBlocksPeer
    SkipAsForeign: false
    ID: HealthBlocksPeerMSP
    MSPDir: ../../.generated/crypto/peerOrganizations/healthblocks.com/msp
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('HealthBlocksPeerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('HealthBlocksPeerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('HealthBlocksPeerMSP.admin','HealthBlocksOrdererMSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('HealthBlocksPeerMSP.member')"
  
  - &MediValeOrderer
    Name: MediValeOrderer
    SkipAsForeign: false
    ID: MediValeOrdererMSP
    MSPDir: ../../.generated/crypto/ordererOrganizations/medivale.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.admin', 'MediValeOrdererMSP.peer', 'MediValeOrdererMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.admin', 'MediValeOrdererMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MediValeOrdererMSP.peer')"
    OrdererEndpoints:
      - "orderer.medivale.com:7050"

  - &MediValePeer
    Name: MediValePeer
    SkipAsForeign: false
    ID: MediValePeerMSP
    MSPDir: ../../.generated/crypto/peerOrganizations/medivale.com/msp
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('MediValePeerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('MediValePeerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('MediValePeerMSP.admin','MediValeOrdererMSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('MediValePeerMSP.member')"
  
  - &HealPointOrderer
    Name: HealPointOrderer
    SkipAsForeign: false
    ID: HealPointOrdererMSP
    MSPDir: ../../.generated/crypto/ordererOrganizations/healpoint.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HealPointOrdererMSP.admin', 'HealPointOrdererMSP.peer', 'HealPointOrdererMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('HealPointOrdererMSP.admin', 'HealPointOrdererMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('HealPointOrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('HealPointOrdererMSP.peer')"
    OrdererEndpoints:
      - "orderer.healpoint.com:7050"
  
  - &HealPointPeer
    Name: HealPointPeer
    SkipAsForeign: false
    ID: HealPointPeerMSP
    MSPDir: ../../.generated/crypto/peerOrganizations/healpoint.com/msp
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('HealPointPeerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('HealPointPeerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('HealPointPeerMSP.admin','HealPointOrdererMSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('HealPointPeerMSP.member')"
  
  - &LifeCareOrderer
    Name: LifeCareOrderer
    SkipAsForeign: false
    ID: LifeCareOrdererMSP
    MSPDir: ../../.generated/crypto/ordererOrganizations/lifecare.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('LifeCareOrdererMSP.admin', 'LifeCareOrdererMSP.peer', 'LifeCareOrdererMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('LifeCareOrdererMSP.admin', 'LifeCareOrdererMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('LifeCareOrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('LifeCareOrdererMSP.peer')"
    OrdererEndpoints:
      - "orderer.lifecare.com:7050"

  - &LifeCarePeer
    Name: LifeCarePeer
    SkipAsForeign: false
    ID: LifeCarePeerMSP
    MSPDir: ../../.generated/crypto/peerOrganizations/lifecare.com/msp
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('LifeCarePeerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('LifeCarePeerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('LifeCarePeerMSP.admin','LifeCareOrdererMSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('LifeCarePeerMSP.member')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  ACLs: &ACLsDefault
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Writers

    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers

    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers

    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetChannelConfig: /Channel/Application/Readers

    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Writers

    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
  
  Organizations:

  Policies: &ApplicationDefaultPolicies
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  Addresses:

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 500
    AbsoluteMaxBytes: 10 MB
    PreferredMaxBytes: 2 MB

  MaxChannels: 0

  EtcdRaft:
    Consenters:
      - Host: orderer.healthblocks.com
        Port: 7050
        ClientTLSCert: ../../.generated/crypto/ordererOrganizations/healthblocks.com/orderers/orderer.healthblocks.com/tls/server.crt
        ServerTLSCert: ../../.generated/crypto/ordererOrganizations/healthblocks.com/orderers/orderer.healthblocks.com/tls/server.crt
      - Host: orderer.medivale.com
        Port: 7050
        ClientTLSCert: ../../.generated/crypto/ordererOrganizations/medivale.com/orderers/orderer.medivale.com/tls/server.crt
        ServerTLSCert: ../../.generated/crypto/ordererOrganizations/medivale.com/orderers/orderer.medivale.com/tls/server.crt
      - Host: orderer.healpoint.com
        Port: 7050
        ClientTLSCert: ../../.generated/crypto/ordererOrganizations/healpoint.com/orderers/orderer.healpoint.com/tls/server.crt
        ServerTLSCert: ../../.generated/crypto/ordererOrganizations/healpoint.com/orderers/orderer.healpoint.com/tls/server.crt
      - Host: orderer.lifecare.com
        Port: 7050
        ClientTLSCert: ../../.generated/crypto/ordererOrganizations/lifecare.com/orderers/orderer.lifecare.com/tls/server.crt
        ServerTLSCert: ../../.generated/crypto/ordererOrganizations/lifecare.com/orderers/orderer.lifecare.com/tls/server.crt

    Options:
      TickInterval: 500ms
      ElectionTick: 10
      HeartbeatTick: 1
      MaxInflightBlocks: 5
      SnapshotIntervalSize: 16 MB

  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  # Policies defines the set of policies at this level of the config tree
  # For Channel policies, their canonical path is
  #   /Channel/<PolicyName>
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  # Capabilities describes the channel level capabilities, see the
  # dedicated Capabilities section elsewhere in this file for a full
  # description
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  HealthBlocksGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *HealthBlocksOrderer
        - *MediValeOrderer
        - *HealPointOrderer
        - *LifeCareOrderer
    Consortiums:
      HealthBlocksConsortium:
        Organizations:
          - *HealthBlocksPeer
          - *MediValePeer
          - *HealPointPeer
          - *LifeCarePeer


  HealthBlocksChannel:
    <<: *ChannelDefaults
    Consortium: HealthBlocksConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *HealthBlocksPeer
        - *MediValePeer
        - *HealPointPeer
        - *LifeCarePeer
